---
title: "Exercise_03"
output: html_document
date: "2024-02-07"
---
```{r message = FALSE, warning=FALSE}
require(dplyr)
require(tidyverse)
require(ggplot2)
```

Step 1
```{r}
load_dictionary <- function(filename) {
  library(tidyverse)
  link <- filename
  return(read.csv(link, sep = ",", header = TRUE, stringsAsFactors = FALSE))
}
```

```{r}
valid_list <- load_dictionary("../data/collins-scrabble-words-2019.txt")
str(valid_list)
```

```{r}
solution_list <- load_dictionary("../data/google-10000-english-usa-no-swears.txt")
str(valid_list)
```

Step 2
```{r}
solution_list <- intersect(solution_list, valid_list)
```
8336 words are in the updated solution_list vector. On the website instruction, Step 1 shows 8336 words already, but I got 

Step 3
```{r}
pick_solution <- function(df) {
  df1 <- subset(df, nchar(df[,1]) == 5)
  df2 <- df1[sample(nrow(df1), 1), ]
  return(strsplit(df2, "")[[1]])
}
```

Bonus with two arguments:
```{r}
pick_solution <- function(df, n) {
  df1 <- subset(df, nchar(df[,1]) == n)
  df2 <- df1[sample(nrow(df1), 1), ]
  #return(str_split(df2, ""))
  return(strsplit(df2, "")[[1]])
}
```

```{r}
solution <- pick_solution(solution_list, 5)
solution[5]
```

Step 4
A helper function:
```{r}
evaluate_guess <- function(df, solution) {
  df1<- strsplit(df, "")[[1]]
  for (i in 1:length(df1)) {
    if (df1[i] == solution[i]) {
      df1[i] <- "*"
    } else if (df1[i] %in% solution) {
      df1[i] <- "+"
    } else {
      df1[i] <- "-"
    }
}
  return(df1)
}
```

```{r}
play_wordle <- function(s, v, num_guesses=6){
  letter_bank <- LETTERS
  History <- c("History:")
  for (i in 1:num_guesses) {
  print(paste("You have", paste(num_guesses+1-i), "chances to guess a word of length 5"))
  print(paste(c("Letters left: ", letter_bank), collapse=" "))
  repeat {
    guess <- toupper(readline(paste("Enter guess number", paste(i), "here, then press <enter>: ")))
    if (guess %in% v[[1]] == TRUE && nchar(guess)==5) break
  }
  guess_letter <- strsplit(guess, "")[[1]]
  result <- evaluate_guess(guess, s)
  print(result)
  History <- append(History, guess)
  History <- append(History, result)
  letter_bank <- setdiff(letter_bank, guess_letter)
  if (setequal(result, c("*", "*", "*","*", "*"))==TRUE){
    print("You won.")
    break
  } else if (i==6){
    print("You lost.")
  }
  }
  print(History)
}
```


```{r}
play_wordle(solution, valid_list, num_guesses=6)
```







